# docker build -f Dockerfile.debug -t ng-preset:debug --build-arg configuration=production .

# Stage for deploy and hosting application
FROM nginx:alpine
COPY ./config/nginx.conf /etc/nginx/nginx.conf
